name = "LinearFold"
uuid = "aebc047d-cbe2-4ea1-a181-a2987ad69fed"
authors = ["Marco Matthies <marco.matthies@gmail.com>"]
version = "0.1.0"

[deps]
LinearFold_jll = "492392ba-fc20-5d72-afbd-f61f3c69e3d5"
LinearPartition_jll = "e9cb6f04-5a86-57c9-b8cc-25aa5bdf9fd6"
LinearSampling_jll = "be43c337-7630-5e25-892b-702745a732dd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
LinearFold_jll = "1.0.0"
LinearPartition_jll = "1.0.0"
Unitful = "1"
julia = "1.7"
